In [0]:
#files!
path = './segismundo.txt'

In [0]:
f = open(path)

In [0]:
lines = [x.rstrip() for x in f]

In [0]:
lines

['\ufeffSueña el rico en su riqueza',
 'que más cuidados le ofrece',
 "sueña el pobre que padece',",
 "su miseria y su pobreza;',",
 "sueña el que a medrar empieza,',",
 "sueña el que afana y pretende,',",
 "sueña el que agravia y ofende,',",
 "'y en el mundo, en conclusión,',",
 "'todos sueñan lo que son,',",
 "'aunque ninguno lo entiende.',"]

In [0]:
import sys
sys.getdefaultencoding()

'utf-8'

In [0]:
type(lines)

list

In [0]:
#numpy
import numpy as np

In [0]:
data = np.random.rand(2,3)

In [0]:
print(data*10)
print('***')
print(data + data)

[[5.96122652 7.46814365 7.84511312]
 [1.10178911 2.66690744 5.30287315]]
***
[[1.1922453  1.49362873 1.56902262]
 [0.22035782 0.53338149 1.06057463]]


In [0]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [0]:
arr2 = np.array(data2)

In [0]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [0]:
print(arr2.ndim)
print(arr2.shape)

2
(2, 4)


In [0]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [0]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [0]:
arr.astype(np.float64)

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [0]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)

In [0]:
print(numeric_strings)

[b'1.25' b'-9.6' b'42']


In [0]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [0]:
#more numpy array!
#ndarray is just a chunk of memory
#strides-> indexing schime
np.ones((3, 4, 5), dtype=np.float64).strides

(160, 40, 8)

In [0]:
'''
C/row major order
Traverse higher dimensions first (e.g., axis 1 before advancing on axis 0)

Fortran/column major order
Traverse higher dimensions last (e.g., axis 0 before advancing on axis 1)
'''

arr = np.arange(12).reshape((3, 4))

In [0]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [0]:
arr.ravel() #C

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [0]:
arr.ravel('F') #Fortran

array([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])

In [0]:
#Join arrays
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

In [0]:
np.vstack((arr1,arr2)) #row-wise

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [0]:
np.hstack((arr1,arr2)) #column-wise

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [0]:
#split
arr = np.random.randn(5, 2)
first, second, third = np.split(arr, [1, 3])

In [0]:
print(first)
print()
print(second)
print()
print(third)

[[0.71703019 2.38387886]]

[[ 0.76297523  0.8693183 ]
 [-2.02039032 -0.39773367]]

[[-1.29150494 -2.51780288]
 [-0.90702813  1.66176387]]


In [0]:
#Broadcasting describes how arithmetic works between arrays of different shapes: array computation
arr = np.random.randn(4, 3)

In [0]:
row_means = arr.mean(1)

In [0]:
row_means.reshape(4,1)

array([[-1.00229935],
       [ 0.16183277],
       [-0.85910596],
       [-0.13487464]])

In [0]:
arr - arr.mean(1).reshape(4,1) #According to the broadcasting rule, the “broadcast dimensions” must be 1 in the smaller array

array([[ 1.03131944,  0.12648983, -1.15780926],
       [ 1.24858241, -0.42148007, -0.82710234],
       [ 1.71424557, -0.58470337, -1.1295422 ],
       [ 0.21742847,  0.14490567, -0.36233414]])

In [0]:
#new-axis
arr = np.zeros((4,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [0]:
arr_3d = arr[:,np.newaxis,:]
arr_3d.shape

(4, 1, 4)

In [0]:
arr_1d = np.random.normal(size=3)

In [0]:
arr_1d

array([ 0.15558795, -0.9191727 ,  2.01572858])

In [0]:
arr_1d[:,np.newaxis]

array([[ 0.15558795],
       [-0.9191727 ],
       [ 2.01572858]])

In [0]:
arr_1d[np.newaxis,:]

array([[ 0.15558795, -0.9191727 ,  2.01572858]])

In [0]:
a.shape

(1, 3)

In [0]:
arr = np.random.rand(3,4,5)

In [0]:
arr

array([[[0.00889111, 0.07443574, 0.28545714, 0.204222  , 0.62939348],
        [0.83741527, 0.96499235, 0.79320402, 0.41348214, 0.62249796],
        [0.8167271 , 0.68110389, 0.45157582, 0.33774241, 0.45653519],
        [0.08436288, 0.914174  , 0.01874728, 0.78137584, 0.95268151]],

       [[0.20828376, 0.93762814, 0.35700995, 0.95003566, 0.57761516],
        [0.44402525, 0.95252374, 0.40141991, 0.49369371, 0.77532791],
        [0.68179918, 0.7408325 , 0.4868319 , 0.99827737, 0.73972207],
        [0.94876568, 0.34988311, 0.29954051, 0.09172657, 0.90398873]],

       [[0.60903976, 0.89018743, 0.5493616 , 0.73384608, 0.27018522],
        [0.71258453, 0.08744883, 0.20598945, 0.27986658, 0.36412102],
        [0.37396769, 0.19226105, 0.63539876, 0.47607562, 0.22874327],
        [0.5292467 , 0.48929   , 0.41272527, 0.34580795, 0.75434733]]])

In [0]:
depth_means = arr.mean(2)

In [0]:
depth_means

array([[0.24047989, 0.72631835, 0.54873688, 0.5502683 ],
       [0.60611453, 0.61339811, 0.72949261, 0.51878092],
       [0.61052402, 0.33000208, 0.38128928, 0.50628345]])

In [0]:
((0.00889111 + 0.07443574 + 0.28545714 + 0.204222 + 0.62939348)/5)

0.240479894

In [0]:
demeanded = arr - depth_means[:,:,np.newaxis]

In [0]:
demeanded.mean(2)

array([[-1.11022302e-17, -2.22044605e-17,  4.44089210e-17,
        -2.22044605e-17],
       [-2.22044605e-17,  0.00000000e+00,  0.00000000e+00,
        -6.66133815e-17],
       [ 4.44089210e-17, -1.11022302e-17, -2.22044605e-17,
         2.22044605e-17]])

In [0]:
#Setting array values by broadcasting
arr = np.zeros((4,3))

In [0]:
arr[:5] = 5

In [0]:
arr

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [0]:
col = np.array([1.28,-0.42,0.44,1.6])

In [0]:
col

array([ 1.28, -0.42,  0.44,  1.6 ])

In [0]:
arr[:] = col[:,np.newaxis]

In [0]:
arr

array([[ 1.28,  1.28,  1.28],
       [-0.42, -0.42, -0.42],
       [ 0.44,  0.44,  0.44],
       [ 1.6 ,  1.6 ,  1.6 ]])

In [0]:
arr[:2] = [[-1.37],[0.509]]

In [0]:
arr

array([[-1.37 , -1.37 , -1.37 ],
       [ 0.509,  0.509,  0.509],
       [ 0.44 ,  0.44 ,  0.44 ],
       [ 1.6  ,  1.6  ,  1.6  ]])

In [0]:
arr[:3] = [[-1.0],[2.0],[3.0]]

In [0]:
arr

array([[-1. , -1. , -1. ],
       [ 2. ,  2. ,  2. ],
       [ 3. ,  3. ,  3. ],
       [ 1.6,  1.6,  1.6]])

In [0]:
arr = np.random.randn(5, 5)

In [5]:
arr

array([[ 0.07973916, -0.61833803,  0.27667609,  0.28729297,  0.9046737 ],
       [ 1.46698487, -1.15886978,  1.08537401,  0.12264401, -0.09495741],
       [-0.70098636,  1.66179734,  1.35256521, -0.09799068,  0.05830313],
       [-1.25306648, -0.57066843, -0.32842466, -0.29283101,  0.95801051],
       [ 1.10808561, -0.40245617, -0.61767072, -0.64813668,  1.34206747]])

In [8]:
arr[::2].sort(1)

None


In [10]:
arr[:,:-1] < arr[:,1:]

array([[ True,  True,  True,  True],
       [False,  True, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [11]:
np.logical_and.reduce(arr[:, :-1] < arr[:, 1:], axis=1)

array([ True, False,  True,  True,  True])

In [14]:
arr

array([[-0.61833803,  0.07973916,  0.27667609,  0.28729297,  0.9046737 ],
       [ 1.46698487, -1.15886978,  1.08537401,  0.12264401, -0.09495741],
       [-0.70098636, -0.09799068,  0.05830313,  1.35256521,  1.66179734],
       [-1.25306648, -0.57066843, -0.32842466, -0.29283101,  0.95801051],
       [-0.64813668, -0.61767072, -0.40245617,  1.10808561,  1.34206747]])

In [12]:
arr[:, :-1] #without last column

array([[-0.61833803,  0.07973916,  0.27667609,  0.28729297],
       [ 1.46698487, -1.15886978,  1.08537401,  0.12264401],
       [-0.70098636, -0.09799068,  0.05830313,  1.35256521],
       [-1.25306648, -0.57066843, -0.32842466, -0.29283101],
       [-0.64813668, -0.61767072, -0.40245617,  1.10808561]])

In [13]:
arr[:, 1:] #without first column

array([[ 0.07973916,  0.27667609,  0.28729297,  0.9046737 ],
       [-1.15886978,  1.08537401,  0.12264401, -0.09495741],
       [-0.09799068,  0.05830313,  1.35256521,  1.66179734],
       [-0.57066843, -0.32842466, -0.29283101,  0.95801051],
       [-0.61767072, -0.40245617,  1.10808561,  1.34206747]])

In [16]:
arr = np.arange(15).reshape((3, 5))
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [21]:
np.add.accumulate(arr, axis=1)

array([[ 0,  1,  3,  6, 10],
       [ 5, 11, 18, 26, 35],
       [10, 21, 33, 46, 60]])

In [23]:
arr = np.arange(3).repeat([1, 2, 2])
print(arr)

[0 1 1 2 2]


In [25]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [24]:
np.multiply.outer(arr, np.arange(5))

array([[0, 0, 0, 0, 0],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 2, 4, 6, 8],
       [0, 2, 4, 6, 8]])

In [27]:
x, y = np.random.randn(3, 4), np.random.randn(5)
print(x)
print(y)

[[ 0.31623021  0.32716116 -0.68018988 -1.53458237]
 [-0.04271147 -0.43827717  1.28533245 -0.49427378]
 [-0.39002926 -0.01848634  0.73601818  0.51103314]]
[-1.73943741  1.64876422  0.85022489  1.90222061  2.41372843]


In [0]:
result = np.subtract.outer(x, y)

In [30]:
print(result.shape)
print(result)

(3, 4, 5)
[[[ 2.05566762 -1.33253401 -0.53399468 -1.5859904  -2.09749822]
  [ 2.06659857 -1.32160306 -0.52306372 -1.57505945 -2.08656726]
  [ 1.05924753 -2.3289541  -1.53041477 -2.58241049 -3.09391831]
  [ 0.20485504 -3.18334659 -2.38480726 -3.43680298 -3.9483108 ]]

 [[ 1.69672594 -1.69147569 -0.89293635 -1.94493208 -2.45643989]
  [ 1.30116024 -2.08704139 -1.28850205 -2.34049778 -2.85200559]
  [ 3.02476986 -0.36343178  0.43510756 -0.61688816 -1.12839598]
  [ 1.24516363 -2.143038   -1.34449867 -2.39649439 -2.90800221]]

 [[ 1.34940815 -2.03879349 -1.24025415 -2.29224987 -2.80375769]
  [ 1.72095107 -1.66725056 -0.86871122 -1.92070695 -2.43221476]
  [ 2.47545559 -0.91274604 -0.11420671 -1.16620243 -1.67771025]
  [ 2.25047055 -1.13773108 -0.33919174 -1.39118747 -1.90269529]]]


In [0]:
arr = np.arange(10)

In [32]:
np.add.reduceat(arr, [0, 5, 8])

array([10, 18, 17])

In [33]:
'''
reduce(x) Aggregate values by successive applications of the operation
accumulate(x) Aggregate values, preserving all partial aggregates
reduceat(x, bins) “Local” reduce or “group by”; reduce contiguous slices of data to produce aggregated array
outer(x, y) Apply operation to all pairs of elements in x and y; the resulting array has shape x.shape + y.shape
'''

'\nreduce(x) Aggregate values by successive applications of the operation\naccumulate(x) Aggregate values, preserving all partial aggregates\nreduceat(x, bins) “Local” reduce or “group by”; reduce contiguous slices of data to produce aggregated array\nouter(x, y) Apply operation to all pairs of elements in x and y; the resulting array has shape x.shape + y.shape\n'

In [37]:
#sorting
arr = np.random.randn(3, 5)
print(arr)

[[ 1.2380359  -0.61002315  0.09024817 -1.18584022  1.25682189]
 [-0.19142352  0.48826175 -1.8378688  -0.36722853  1.56165704]
 [-0.61708374 -1.30104883 -0.43625426  0.99521352  1.24693931]]


In [36]:
#by column
arr.sort(axis=1)
print(arr)

[[-0.53656666 -0.43521588 -0.04069185  0.19808883  0.28000399]
 [ 0.1374968   0.48823778  0.50439382  0.63621355  0.85145561]
 [-1.25495857 -0.78631814 -0.45081529 -0.43031316  0.10414424]]


In [39]:
#by row
arr.sort(axis=0)
print(arr)

[[-0.61708374 -1.30104883 -1.8378688  -1.18584022  1.24693931]
 [-0.19142352 -0.61002315 -0.43625426 -0.36722853  1.25682189]
 [ 1.2380359   0.48826175  0.09024817  0.99521352  1.56165704]]


In [40]:
#reverse == descending order
arr[:,::-1]

array([[ 1.24693931, -1.18584022, -1.8378688 , -1.30104883, -0.61708374],
       [ 1.25682189, -0.36722853, -0.43625426, -0.61002315, -0.19142352],
       [ 1.56165704,  0.99521352,  0.09024817,  0.48826175,  1.2380359 ]])

In [0]:
#index
values = np.array([5, 0, 1, 3, 2])
indexer = values.argsort()

In [42]:
indexer

array([1, 2, 4, 3, 0])

In [43]:
values[indexer]

array([0, 1, 2, 3, 5])

In [0]:
arr = np.random.randn(3, 5)

In [0]:
arr[0] = values

In [47]:
arr

array([[ 5.        ,  0.        ,  1.        ,  3.        ,  2.        ],
       [ 0.54717499, -0.20714246, -0.54603929,  0.9896077 , -1.04401928],
       [ 1.8847097 , -0.71023186,  0.74293582,  0.87913725, -1.27089399]])

In [48]:
arr[:,arr[0].argsort()]

array([[ 0.        ,  1.        ,  2.        ,  3.        ,  5.        ],
       [-0.20714246, -0.54603929, -1.04401928,  0.9896077 ,  0.54717499],
       [-0.71023186,  0.74293582, -1.27089399,  0.87913725,  1.8847097 ]])

In [0]:
#character sort: lexsort()
first_name = np.array(['Bob', 'Jane', 'Steve', 'Bill', 'Barbara'])
last_name = np.array(['Jones', 'Arnold', 'Arnold', 'Jones', 'Walters'])

In [0]:
sorter = np.lexsort((first_name, last_name))

In [52]:
print(sorter)

[1 2 3 0 4]


In [55]:
zip(last_name[sorter], first_name[sorter])

In [0]:
#sort!
values = np.array(['2:first','2:second','1:first','1:second','1:third'])
key = np.array([2,2,1,1,1])

In [57]:
indexer = key.argsort(kind = 'mergesort') #the only stable sort
print(indexer)

[2 3 4 0 1]


In [58]:
values.take(indexer)

array(['1:first', '1:second', '1:third', '2:first', '2:second'],
      dtype='<U8')

In [61]:
indexer.shape

(5,)