In [0]:
#files!
path = './segismundo.txt'

In [0]:
f = open(path)

In [0]:
lines = [x.rstrip() for x in f]

In [0]:
lines

['\ufeffSueña el rico en su riqueza',
 'que más cuidados le ofrece',
 "sueña el pobre que padece',",
 "su miseria y su pobreza;',",
 "sueña el que a medrar empieza,',",
 "sueña el que afana y pretende,',",
 "sueña el que agravia y ofende,',",
 "'y en el mundo, en conclusión,',",
 "'todos sueñan lo que son,',",
 "'aunque ninguno lo entiende.',"]

In [0]:
import sys
sys.getdefaultencoding()

'utf-8'

In [0]:
type(lines)

list

In [0]:
#numpy
import numpy as np

In [0]:
data = np.random.rand(2,3)

In [0]:
print(data*10)
print('***')
print(data + data)

[[5.96122652 7.46814365 7.84511312]
 [1.10178911 2.66690744 5.30287315]]
***
[[1.1922453  1.49362873 1.56902262]
 [0.22035782 0.53338149 1.06057463]]


In [0]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [0]:
arr2 = np.array(data2)

In [0]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [0]:
print(arr2.ndim)
print(arr2.shape)

2
(2, 4)


In [0]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [0]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [0]:
arr.astype(np.float64)

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [0]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)

In [0]:
print(numeric_strings)

[b'1.25' b'-9.6' b'42']


In [0]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [0]:
#more numpy array!
#ndarray is just a chunk of memory
#strides-> indexing schime
np.ones((3, 4, 5), dtype=np.float64).strides

(160, 40, 8)

In [0]:
'''
C/row major order
Traverse higher dimensions first (e.g., axis 1 before advancing on axis 0)

Fortran/column major order
Traverse higher dimensions last (e.g., axis 0 before advancing on axis 1)
'''

arr = np.arange(12).reshape((3, 4))

In [0]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [0]:
arr.ravel() #C

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [0]:
arr.ravel('F') #Fortran

array([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])

In [0]:
#Join arrays
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

In [0]:
np.vstack((arr1,arr2)) #row-wise

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [0]:
np.hstack((arr1,arr2)) #column-wise

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [0]:
#split
arr = np.random.randn(5, 2)
first, second, third = np.split(arr, [1, 3])

In [0]:
print(first)
print()
print(second)
print()
print(third)

[[0.71703019 2.38387886]]

[[ 0.76297523  0.8693183 ]
 [-2.02039032 -0.39773367]]

[[-1.29150494 -2.51780288]
 [-0.90702813  1.66176387]]


In [0]:
#Broadcasting describes how arithmetic works between arrays of different shapes: array computation
arr = np.random.randn(4, 3)

In [0]:
row_means = arr.mean(1)

In [0]:
row_means.reshape(4,1)

array([[-1.00229935],
       [ 0.16183277],
       [-0.85910596],
       [-0.13487464]])

In [0]:
arr - arr.mean(1).reshape(4,1) #According to the broadcasting rule, the “broadcast dimensions” must be 1 in the smaller array

array([[ 1.03131944,  0.12648983, -1.15780926],
       [ 1.24858241, -0.42148007, -0.82710234],
       [ 1.71424557, -0.58470337, -1.1295422 ],
       [ 0.21742847,  0.14490567, -0.36233414]])

In [2]:
#new-axis
arr = np.zeros((4,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [3]:
arr_3d = arr[:,np.newaxis,:]
arr_3d.shape

(4, 1, 4)

In [0]:
arr_1d = np.random.normal(size=3)

In [5]:
arr_1d

array([ 0.15558795, -0.9191727 ,  2.01572858])

In [6]:
arr_1d[:,np.newaxis]

array([[ 0.15558795],
       [-0.9191727 ],
       [ 2.01572858]])

In [10]:
arr_1d[np.newaxis,:]

array([[ 0.15558795, -0.9191727 ,  2.01572858]])

In [9]:
a.shape

(1, 3)

In [0]:
arr = np.random.rand(3,4,5)

In [14]:
arr

array([[[0.00889111, 0.07443574, 0.28545714, 0.204222  , 0.62939348],
        [0.83741527, 0.96499235, 0.79320402, 0.41348214, 0.62249796],
        [0.8167271 , 0.68110389, 0.45157582, 0.33774241, 0.45653519],
        [0.08436288, 0.914174  , 0.01874728, 0.78137584, 0.95268151]],

       [[0.20828376, 0.93762814, 0.35700995, 0.95003566, 0.57761516],
        [0.44402525, 0.95252374, 0.40141991, 0.49369371, 0.77532791],
        [0.68179918, 0.7408325 , 0.4868319 , 0.99827737, 0.73972207],
        [0.94876568, 0.34988311, 0.29954051, 0.09172657, 0.90398873]],

       [[0.60903976, 0.89018743, 0.5493616 , 0.73384608, 0.27018522],
        [0.71258453, 0.08744883, 0.20598945, 0.27986658, 0.36412102],
        [0.37396769, 0.19226105, 0.63539876, 0.47607562, 0.22874327],
        [0.5292467 , 0.48929   , 0.41272527, 0.34580795, 0.75434733]]])

In [0]:
depth_means = arr.mean(2)

In [13]:
depth_means

array([[0.24047989, 0.72631835, 0.54873688, 0.5502683 ],
       [0.60611453, 0.61339811, 0.72949261, 0.51878092],
       [0.61052402, 0.33000208, 0.38128928, 0.50628345]])

In [19]:
((0.00889111 + 0.07443574 + 0.28545714 + 0.204222 + 0.62939348)/5)

0.240479894

In [0]:
demeanded = arr - depth_means[:,:,np.newaxis]

In [21]:
demeanded.mean(2)

array([[-1.11022302e-17, -2.22044605e-17,  4.44089210e-17,
        -2.22044605e-17],
       [-2.22044605e-17,  0.00000000e+00,  0.00000000e+00,
        -6.66133815e-17],
       [ 4.44089210e-17, -1.11022302e-17, -2.22044605e-17,
         2.22044605e-17]])

In [0]:
#Setting array values by broadcasting
arr = np.zeros((4,3))

In [0]:
arr[:5] = 5

In [25]:
arr

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [0]:
col = np.array([1.28,-0.42,0.44,1.6])

In [27]:
col

array([ 1.28, -0.42,  0.44,  1.6 ])

In [0]:
arr[:] = col[:,np.newaxis]

In [29]:
arr

array([[ 1.28,  1.28,  1.28],
       [-0.42, -0.42, -0.42],
       [ 0.44,  0.44,  0.44],
       [ 1.6 ,  1.6 ,  1.6 ]])

In [0]:
arr[:2] = [[-1.37],[0.509]]

In [31]:
arr

array([[-1.37 , -1.37 , -1.37 ],
       [ 0.509,  0.509,  0.509],
       [ 0.44 ,  0.44 ,  0.44 ],
       [ 1.6  ,  1.6  ,  1.6  ]])

In [0]:
arr[:3] = [[-1.0],[2.0],[3.0]]

In [50]:
arr

array([[-1. , -1. , -1. ],
       [ 2. ,  2. ,  2. ],
       [ 3. ,  3. ,  3. ],
       [ 1.6,  1.6,  1.6]])