In [0]:
import numpy as np

In [3]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]],
                  [[7, 8, 9],[10, 11, 12]]])
print(arr3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [4]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [0]:
#Indexing with slices