In [0]:
#files!
path = './segismundo.txt'

In [0]:
f = open(path)

In [0]:
lines = [x.rstrip() for x in f]

In [5]:
lines

['\ufeffSueña el rico en su riqueza',
 'que más cuidados le ofrece',
 "sueña el pobre que padece',",
 "su miseria y su pobreza;',",
 "sueña el que a medrar empieza,',",
 "sueña el que afana y pretende,',",
 "sueña el que agravia y ofende,',",
 "'y en el mundo, en conclusión,',",
 "'todos sueñan lo que son,',",
 "'aunque ninguno lo entiende.',"]

In [6]:
import sys
sys.getdefaultencoding()

'utf-8'

In [7]:
type(lines)

list

In [0]:
#numpy
import numpy as np

In [0]:
data = np.random.rand(2,3)

In [14]:
print(data*10)
print('***')
print(data + data)

[[5.96122652 7.46814365 7.84511312]
 [1.10178911 2.66690744 5.30287315]]
***
[[1.1922453  1.49362873 1.56902262]
 [0.22035782 0.53338149 1.06057463]]


In [0]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [0]:
arr2 = np.array(data2)

In [22]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [25]:
print(arr2.ndim)
print(arr2.shape)

2
(2, 4)


In [0]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [45]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [46]:
arr.astype(np.float64)

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [0]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)

In [49]:
print(numeric_strings)

[b'1.25' b'-9.6' b'42']


In [50]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])